version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq-consumer

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
