version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq-consumer
    environment:
      - RABBITMQ_HOST=rabbitmqConsumer
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=beer
