server:
  port: 8081

spring:
  jpa:
    ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace

    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest

      exchange:
        producer: ex.producer.rabbitmqtest

      deadletter:
        producer: dl.producer.rabbitmqtest

      routing-key:
        producer: rk.producer.rabbitmqtest