server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://becks:becks@beertechbancobeerbecks.0beio.azure.mongodb.net/<dbname>?retryWrites=true&w=majority
      database: becks

beertech:
  swagger:
    baseUrl: ${SWAGGER_BASE_URL:localhost:${server.port}}
    apiInfo: REST API for Bank Becks Service Microservice
    apiTitle: BeerTech Bank Becks Service


security:
  jwt:
    expiry: 3000
    key: dmljdG9yY2FydmFsaG8=